name: Update mods via GitHub api

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'site'
    - name: Copy ModUpdater
      run: |
        cp -R site/Programs/ModUpdater ModUpdater
    - name: Save token
      run: |
        echo "Bearer ${{ secrets.GITHUB_TOKEN }}" >> ModUpdater/token.txt
    - name: Show files
      run: |
        cd ModUpdater
        ls
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Update mods
      working-directory: 'ModUpdater'
      run: |
        dotnet ModUpdater.dll
    - name: Show mods
      run: |
        cat ModUpdater/mods_updated.json
